[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=~/.config/qt6ct/colors/tokyonight-night.conf
standard_dialogs=default

[Fonts]
general="Noto Sans,12"
fixed="FiraCode Nerd Font Mono,12"
